swagger: '2.0'
info:
  description: '饱了么API文档'
  version: '花Q'
  title: 'Baoleme'
host: 'baoleme.andiedie.cn'
basePath: '/'
tags:
- name: 'Restaurant Account'
  description: '餐厅账号'
- name: 'Customer Account'
  description: '用户账号'
schemes:
- 'https'
paths:
  /restaurant:
    post:
      tags:
      - 'Restaurant Account'
      summary: '餐厅注册'
      parameters:
      - in: 'body'
        name: 'body'
        description: '注册信息'
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/RestaurantWithoutId'
          - properties:
              password:
                type: 'string'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
  /restaurant/session:
    post:
      tags:
      - 'Restaurant Account'
      summary: '登录'
      parameters:
      - in: 'body'
        name: 'body'
        description: '登录信息'
        required: true
        schema:
          type: 'object'
          properties:
            email:
              type: 'string'
            password:
              type: 'string'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - 'Restaurant Account'
      summary: '退出登录'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
  /restaurant/self:
    get:
      tags:
      - 'Restaurant Account'
      summary: '获取餐厅自身信息'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/Restaurant'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
  /customer/self:
    get:
      tags:
      - 'Customer Account'
      summary: '获取用户自身信息'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/User'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
  /customer/login:
    post:
      tags:
      - 'Customer Account'
      summary: '登录，若未注册则会自动注册'
      parameters:
      - in: 'body'
        name: 'body'
        description: 'wx.login返回的code'
        required: true
        schema:
          type: 'object'
          properties:
            code:
              type: 'string'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/User'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ErrorResponse:
    type: 'object'
    properties:
      message:
        type: 'string'
  RestaurantWithoutId:
    type: 'object'
    properties:
      email:
        type: 'string'
      name:
        type: 'string'
  Restaurant:
    allOf:
    - $ref: '#/definitions/RestaurantWithoutId'
    - properties:
        restaurant_id:
          type: 'integer'
  User:
    type: 'object'
    properties:
      customer_id:
        type: 'integer'